### ISSUE TITLE
Version for 1.12.2

### ISSUE THREAD

**Issue by GreyMamoN** [Thutmose/ThutCrafts#2]
## **Version for 1.12 does not work for 1.12.2, so it should be?**

[07:39:04] [Server thread/ERROR]: Encountered an unexpected exception
net.minecraftforge.fml.common.WrongMinecraftVersionException: Wrong Minecraft version for thutcrafts
Wrong Minecraft Versions!
Mod: thutcrafts
Location: ~/MCSRV/1.12.2/mods/1.12.2/thutcrafts-0.1.0.jar
Expected: [1.11,1.12]
Current: Minecraft 1.12.2

	at net.minecraftforge.fml.common.Loader.sortModList(Loader.java:242) ~[Loader.class:?]
	at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:545) ~[Loader.class:?]
	at net.minecraftforge.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:97) ~[FMLServerHandler.class:?]
	at net.minecraftforge.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:331) ~[FMLCommonHandler.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:125) ~[nz.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:484) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_151]

**Comment by Thutmose** [comment]
I will see about recompiling crafts for 1.12.2, it seems because it also supported 1.11, it only works for exactly 1.12 instead of 1.12.2
